### ISSUE TITLE
Acronym update: ES = Eric Schmidt or Edward Snowden

### ISSUE THREAD

**Issue by colinskow** [qanonmap/qanonmap.github.io#7]
Acronym update: ES = Eric Schmidt or Edward Snowden

**Comment by qanonmap** [comment]
Snowden is always referred to as "@Snowden".

**Comment by qanonmap** [comment]
Due to multiple anons being confused, this was changed to ES = Eric Schmidt or Edward Snowden recently (see 607f7a64fea10c655dc3b99fd16f159d89c77414).

Q has, however, just confirmed that `@Snowden` does indeed always refer to Snowden and ES always to Schmidt. See b3dc73669f4e7bf2a76cb51e21e160d39c588e9c for the change.
