### ISSUE TITLE
Missing posts from qanonmap

### ISSUE THREAD

**Issue by CodeLiam** [qanonmap/qanonmap.github.io#8]
These 2 posts came up in the middle of the night, and were loading, now they don't appear to be.  I've tried Firefox and Chrome and neither show up now when searching for new posts

https://8ch.net//qresearch/res/457699.html#458430

https://8ch.net//qresearch/res/457699.html#458475

**Comment by qanonmap** [comment]
It is highly encouraged not to use F5 to refresh the browser. This is specific to qanonmap, because it has a checker function built-in that will add posts from 8ch directly. This way, end users can see Q posts on the site, even when they haven't been added to the repo yet. These two are new, and will be added shortly.

**Comment by qanonmap** [comment]
Resolved: b6e4bfb06b2fc117536adba1cc2b47ecf9fb9484.
